### PR TITLE
348 support newer java versions

### PR DESCRIPTION
**Pull request by Moritz-Schrauth-GIP**
* Remove explicit errors when Java version can't be determined / isn't officially supported (`prerequisites_lib.sh`, `InMemoryCompilationSet.java`),
* Add note about new `java` CLI-Args (`README.md`),
* Use new ThreadID-Function for newer Java-Versions (`XynaThreadPoolExecutor.java`)

### CODE REVIEW

**Review by corneliuslippert-gip — APPROVED** [review]

**Comment by csc-gip** [comment]
I had an error testing the default build with Java 19. I don't konw if this is ok for now or a spot that was missed.
```
2023-07-20T11:14:09.8159847Z buildJar:
2023-07-20T11:14:09.8216071Z     [mkdir] Created dir: /home/runner/work/xyna-factory-build/xyna-factory-build/server/classes
2023-07-20T11:14:09.8245000Z      [echo] NOT using Libraries
2023-07-20T11:14:09.8294121Z    [delete] Deleting directory /home/runner/work/xyna-factory-build/xyna-factory-build/server/classes
2023-07-20T11:14:09.8302481Z     [mkdir] Created dir: /home/runner/work/xyna-factory-build/xyna-factory-build/server/classes
2023-07-20T11:14:09.9953367Z      [copy] Copied 256 empty directories to 256 empty directories under /home/runner/work/xyna-factory-build/xyna-factory-build/server/classes
2023-07-20T11:14:09.9981233Z     [javac] jar:file:/home/runner/work/xyna-factory-build/xyna-factory-build/installation/build/lib/xynautils-build-2.3.2.0.jar!/com/gip/xyna/utils/build/buildMacros.xml:606: warning: 'includeantruntime' was not set, defaulting to build.sysclasspath=last; set to false for repeatable builds
2023-07-20T11:14:10.2631450Z     [javac] Compiling 2921 source files to /home/runner/work/xyna-factory-build/xyna-factory-build/server/classes
2023-07-20T11:14:10.6705575Z     [javac] warning: target release 11 conflicts with default source release 19
2023-07-20T11:14:10.6741773Z 
2023-07-20T11:14:10.6742409Z BUILD FAILED
2023-07-20T11:14:10.6744001Z /home/runner/work/xyna-factory-build/xyna-factory-build/server/build.xml:73: The following error occurred while executing this line:
2023-07-20T11:14:10.6745794Z jar:file:/home/runner/work/xyna-factory-build/xyna-factory-build/installation/build/lib/xynautils-build-2.3.2.0.jar!/com/gip/xyna/utils/build/buildMacros.xml:606: Compile failed; see the compiler error output for details.
```

**Comment by Moritz-Schrauth-GIP** [comment]
The issues seems to be, that the compiler expects the source files to contain Java 19 Features which won't work in Java 11. 
Building with a Java Version different from 11 wasn't tested. We only checked, that the Factory can also run in a modern JRE now.

It seems like this can be fixed, by also adding the `-source` option in commands like this: 
https://github.com/Xyna-Factory/xyna-factory/blob/80d555ca4b1795d9b44ad9e338a3fcc7ea2a8027/xynautils/install/build/buildMacros.xml#L602C1-L614C32

**Comment by csc-gip** [comment]
I think the problem is here:
https://github.com/Xyna-Factory/xyna-factory/blob/80d555ca4b1795d9b44ad9e338a3fcc7ea2a8027/server/build.xml#L73
The build.xml for the server explicitly states 11 as target.

**Comment by Moritz-Schrauth-GIP** [comment]
I guess, we have 2 options here:
* remove the `target` option: this would have the same effect as setting the target to the version of the JDK with which the factory is built. If we would then build with Java19, we would have a build, that can only run with Java19 or newer.
* add a `source` options, that is also set to `11`. That way, we would also make sure, that the Factory can always run with Java11 because no-one can accidentally use newer features within their code. 

Issue is: [`target` must be greater or equal to `source`](https://docs.oracle.com/en/java/javase/19/docs/specs/man/javac.html#option-target). But if they are not specified, the current Java-Version is taken.

I guess, it depends on what we want.

**Pull request merged**
